"""
Unit tests for parse_sections.py

Includes an integration test against files/mock_document.pdf.
Generate it first with:
    python generate_mock_pdf.py
"""

import json
import tempfile
from pathlib import Path

import pymupdf
import pytest

from parse_sections import (
    _normalise_key,
    _section_depth,
    extract_blocks,
    parse_sections,
)

# Path to the mock PDF generated by generate_mock_pdf.py
MOCK_PDF = Path(__file__).parent.parent / "files" / "mock_document.pdf"


# ─────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────

def _make_pdf(pages: list[list[str]]) -> str:
    """Write an in-memory PDF where each inner list is one page's blocks."""
    doc = pymupdf.Document()
    for page_blocks in pages:
        page = doc.new_page()
        y = 50.0
        for block_text in page_blocks:
            page.insert_text((50, y), block_text)
            y += 60.0
    tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
    doc.save(tmp.name)
    tmp.close()
    return tmp.name


# ─────────────────────────────────────────────
# TestHelpers
# ─────────────────────────────────────────────

class TestHelpers:
    def test_normalise_strips_trailing_dot(self):
        assert _normalise_key("1.") == "1"

    def test_normalise_leaves_subsection_unchanged(self):
        assert _normalise_key("1.1") == "1.1"

    def test_normalise_leaves_deep_key_unchanged(self):
        assert _normalise_key("3.3.1") == "3.3.1"

    def test_depth_top_level(self):
        assert _section_depth("1") == 1

    def test_depth_second_level(self):
        assert _section_depth("1.1") == 2

    def test_depth_third_level(self):
        assert _section_depth("3.3.1") == 3

    def test_depth_fourth_level(self):
        assert _section_depth("1.2.3.4") == 4


# ─────────────────────────────────────────────
# TestParseSections
# ─────────────────────────────────────────────

class TestParseSections:
    def test_top_level_sections_become_keys(self):
        blocks = [
            "1. Introduction\nThis document describes the facility.",
            "2. The Facility\nThe lender agrees to provide...",
        ]
        result = parse_sections(blocks)
        assert "1" in result
        assert "2" in result

    def test_subsections_become_keys(self):
        blocks = [
            "1. Introduction\nOverview text.",
            "1.1 Background\nBackground detail.",
            "1.2 Scope\nScope detail.",
        ]
        result = parse_sections(blocks)
        assert "1" in result
        assert "1.1" in result
        assert "1.2" in result

    def test_deep_sections_folded_into_parent(self):
        blocks = [
            "1.1 Payment Obligations\nGeneral text.",
            "1.1.1 Principal\nPrincipal repayment terms.",
            "1.1.2 Interest\nInterest accrual terms.",
        ]
        result = parse_sections(blocks)
        assert "1.1" in result
        assert "1.1.1" not in result
        assert "1.1.2" not in result

    def test_deep_section_text_present_under_parent(self):
        blocks = [
            "3.3 Covenants\nGeneral covenant text.",
            "3.3.1 DSCR\nThe DSCR shall not fall below 1.25x.",
            "3.3.2 LTV\nThe LTV shall not exceed 65%.",
        ]
        result = parse_sections(blocks)
        assert "The DSCR shall not fall below 1.25x." in result["3.3"]
        assert "The LTV shall not exceed 65%." in result["3.3"]

    def test_preamble_before_first_section(self):
        blocks = [
            "This agreement is dated 1 January 2026.",
            "1. Definitions\nDefined terms follow.",
        ]
        result = parse_sections(blocks)
        assert "preamble" in result
        assert "1 January 2026" in result["preamble"]

    def test_body_text_between_sections_goes_to_current(self):
        blocks = [
            "2. Representations\nThe borrower represents that:",
            "All statements are true and accurate.",
            "2.1 Financial Condition\nNo material adverse change.",
        ]
        result = parse_sections(blocks)
        assert "All statements are true and accurate." in result["2"]

    def test_section_keys_are_normalised(self):
        # "1." with trailing dot should become key "1", not "1."
        blocks = ["1. Introduction\nText."]
        result = parse_sections(blocks)
        assert "1" in result
        assert "1." not in result

    def test_empty_blocks_list_returns_empty_dict(self):
        assert parse_sections([]) == {}

    def test_section_heading_text_included_in_value(self):
        blocks = ["2.3 Security\nThe borrower shall grant a first charge."]
        result = parse_sections(blocks)
        assert "Security" in result["2.3"]

    def test_multiple_pages_sections_merged_correctly(self):
        # Simulate blocks that span a page boundary within the same section
        blocks = [
            "4. Events of Default\nThe following events constitute default:",
            "Failure to pay any amount when due.",       # continuation on next page
            "4.1 Payment Default\nNon-payment of principal.",
        ]
        result = parse_sections(blocks)
        assert "Failure to pay any amount when due." in result["4"]
        assert "4.1" in result

    def test_section_with_only_number_no_heading_text(self):
        # Edge case: heading line is just the number, text follows on next line
        blocks = ["1.\nThis section covers general provisions."]
        result = parse_sections(blocks)
        assert "1" in result


# ─────────────────────────────────────────────
# TestExtractBlocks
# ─────────────────────────────────────────────

class TestExtractBlocks:
    def test_single_page_blocks_extracted(self):
        path = _make_pdf([["1. Introduction\nOverview.", "1.1 Background\nDetails."]])
        try:
            blocks = extract_blocks(path)
            assert len(blocks) >= 1
            full = " ".join(blocks)
            assert "Introduction" in full
        finally:
            Path(path).unlink(missing_ok=True)

    def test_multi_page_blocks_in_order(self):
        path = _make_pdf([
            ["1. First Section\nContent A."],
            ["2. Second Section\nContent B."],
        ])
        try:
            blocks = extract_blocks(path)
            full = " ".join(blocks)
            assert "First Section" in full
            assert "Second Section" in full
        finally:
            Path(path).unlink(missing_ok=True)

    def test_empty_pdf_returns_no_blocks(self):
        doc = pymupdf.Document()
        doc.new_page()  # blank page
        import tempfile
        tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
        doc.save(tmp.name)
        tmp.close()
        try:
            blocks = extract_blocks(tmp.name)
            assert blocks == []
        finally:
            Path(tmp.name).unlink(missing_ok=True)


# ─────────────────────────────────────────────
# TestMarginFiltering
# ─────────────────────────────────────────────

def _make_pdf_with_blocks(block_positions: list[tuple[float, str]]) -> str:
    """
    Write a PDF where each tuple is (y_position, text).
    Page height is the PyMuPDF default (842 pt for A4).
    """
    doc = pymupdf.Document()
    page = doc.new_page(width=595, height=842)
    for y, text in block_positions:
        page.insert_text((50, y), text, fontsize=10)
    tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
    doc.save(tmp.name)
    tmp.close()
    return tmp.name


class TestMarginFiltering:
    # Page height = 842 pt.  Default margins: header=50, footer=50.
    # Footer zone starts at y0 >= 842 - 50 = 792.

    def test_header_block_excluded(self):
        """A block whose bottom edge (y1) falls within the top 50 pt is skipped."""
        # insert_text puts the baseline at y; for fontsize=10 the block y0≈y-10, y1≈y
        # Place the text so its entire bbox is in [0, 50]: baseline at y=40
        path = _make_pdf_with_blocks([(40, "HEADER TEXT")])
        try:
            blocks = extract_blocks(path)
            assert not any("HEADER TEXT" in b for b in blocks)
        finally:
            Path(path).unlink(missing_ok=True)

    def test_footer_block_excluded(self):
        """A block whose top edge (y0) is at or beyond the footer threshold is skipped."""
        # Baseline at 830 → y0 ≈ 820, well past the 792 threshold.
        path = _make_pdf_with_blocks([(830, "Page 1")])
        try:
            blocks = extract_blocks(path)
            assert not any("Page 1" in b for b in blocks)
        finally:
            Path(path).unlink(missing_ok=True)

    def test_body_block_near_top_included(self):
        """A block just outside the header margin (y > 50) is kept."""
        # Baseline at 120 → bbox safely below header margin
        path = _make_pdf_with_blocks([(120, "1. Introduction")])
        try:
            blocks = extract_blocks(path)
            assert any("Introduction" in b for b in blocks)
        finally:
            Path(path).unlink(missing_ok=True)

    def test_body_block_near_bottom_included(self):
        """A block that ends before the footer zone is kept."""
        # Baseline at 750 → y0 ≈ 740, below footer threshold of 792
        path = _make_pdf_with_blocks([(750, "Last body line.")])
        try:
            blocks = extract_blocks(path)
            assert any("Last body line." in b for b in blocks)
        finally:
            Path(path).unlink(missing_ok=True)

    def test_zero_header_margin_includes_all_top_blocks(self):
        """header_margin=0 disables header filtering — top blocks are kept."""
        path = _make_pdf_with_blocks([(40, "TOP CONTENT")])
        try:
            blocks = extract_blocks(path, header_margin=0)
            assert any("TOP CONTENT" in b for b in blocks)
        finally:
            Path(path).unlink(missing_ok=True)

    def test_zero_footer_margin_includes_all_bottom_blocks(self):
        """footer_margin=0 disables footer filtering — bottom blocks are kept."""
        path = _make_pdf_with_blocks([(830, "BOTTOM CONTENT")])
        try:
            blocks = extract_blocks(path, footer_margin=0)
            assert any("BOTTOM CONTENT" in b for b in blocks)
        finally:
            Path(path).unlink(missing_ok=True)

    def test_custom_large_margin_excludes_body(self):
        """With a very large header_margin, body text near the top is also excluded."""
        # Baseline at 200 → y1 ≈ 200; excluded when header_margin=250
        path = _make_pdf_with_blocks([(200, "Body text.")])
        try:
            blocks = extract_blocks(path, header_margin=250)
            assert not any("Body text." in b for b in blocks)
        finally:
            Path(path).unlink(missing_ok=True)


# ─────────────────────────────────────────────
# TestIntegration — uses the generated mock PDF
# ─────────────────────────────────────────────

@pytest.mark.skipif(not MOCK_PDF.exists(), reason="mock_document.pdf not found — run generate_mock_pdf.py first")
class TestIntegration:
    """End-to-end tests against files/mock_document.pdf."""

    @pytest.fixture(scope="class")
    def sections(self):
        blocks = extract_blocks(str(MOCK_PDF))
        return parse_sections(blocks)

    def test_all_top_level_sections_present(self, sections):
        for key in ["1", "2", "3", "4", "5", "6"]:
            assert key in sections, f"Missing top-level section: {key}"

    def test_all_subsections_present(self, sections):
        expected = [
            "1.1", "1.2", "1.3",
            "2.1", "2.2", "2.3",
            "3.1", "3.2", "3.3", "3.4",
            "4.1", "4.2",
            "5.1", "5.2",
            "6.1", "6.2", "6.3",
        ]
        for key in expected:
            assert key in sections, f"Missing subsection: {key}"

    def test_deep_sections_not_separate_keys(self, sections):
        for key in ["3.3.1", "3.3.2", "3.3.3"]:
            assert key not in sections, f"Deep section should be folded, not a key: {key}"

    def test_deep_section_text_present_in_parent(self, sections):
        text = sections["3.3"]
        assert "DSCR" in text,  "3.3.1 DSCR content missing from 3.3"
        assert "LTV"  in text,  "3.3.2 LTV content missing from 3.3"
        assert "ICR"  in text,  "3.3.3 ICR content missing from 3.3"

    def test_preamble_captured(self, sections):
        assert "preamble" in sections
        assert "ABC BANK" in sections["preamble"]

    def test_section_text_contains_heading(self, sections):
        assert "DEFINITIONS" in sections["1"]
        assert "FACILITY"    in sections["2"]
        assert "INTEREST"    in sections["3"]
        assert "REPAYMENT"   in sections["4"]

    def test_interest_rate_detail_in_correct_section(self, sections):
        assert "SORA" in sections["3.1"]
        assert "SORA" not in sections["3.2"]

    def test_financial_covenant_values_in_3_3(self, sections):
        text = sections["3.3"]
        assert "1.25" in text   # DSCR floor
        assert "65%"  in text   # LTV cap
        assert "2.00" in text   # ICR floor

    def test_header_footer_text_absent_from_sections(self, sections):
        """Footer sentinel text must not appear in parsed sections."""
        all_text = " ".join(sections.values())
        # The mock PDF footer is: "Confidential  |  ABC Bank Limited  |  Page N"
        # The pipe-separated pattern only appears in the footer strip, never in body text.
        assert "Confidential  |" not in all_text, \
            "Footer text leaked into section content"

    def test_section_count_with_margins(self):
        """Parsing with default margins yields the same section count as without
        margins (when the mock PDF has no body text inside the margin strips)."""
        blocks_filtered   = extract_blocks(str(MOCK_PDF))
        blocks_no_margins = extract_blocks(str(MOCK_PDF), header_margin=0, footer_margin=0)
        # With the mock PDF, body starts at y≈80 so both calls should return
        # the same body blocks; the only difference is header/footer blocks.
        secs_filtered   = parse_sections(blocks_filtered)
        secs_no_margins = parse_sections(blocks_no_margins)
        # The filtered parse must contain all expected body sections.
        for key in ["1", "2", "3", "3.1", "3.3", "4.1"]:
            assert key in secs_filtered, f"Section {key!r} missing after filtering"
        # The unfiltered parse may have extra noise keys but must have at least
        # as many sections as the filtered one.
        assert len(secs_no_margins) >= len(secs_filtered)
