"""
Unit tests for parse_sections.py

Includes an integration test against files/mock_document.pdf.
Generate it first with:
    python generate_mock_pdf.py
"""

import json
import tempfile
from pathlib import Path

import pymupdf
import pytest

from parse_sections import (
    _normalise_key,
    _section_depth,
    extract_blocks,
    parse_sections,
)

# Path to the mock PDF generated by generate_mock_pdf.py
MOCK_PDF = Path(__file__).parent.parent / "files" / "mock_document.pdf"


# ─────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────

def _make_pdf(pages: list[list[str]]) -> str:
    """Write an in-memory PDF where each inner list is one page's blocks."""
    doc = pymupdf.Document()
    for page_blocks in pages:
        page = doc.new_page()
        y = 50.0
        for block_text in page_blocks:
            page.insert_text((50, y), block_text)
            y += 60.0
    tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
    doc.save(tmp.name)
    tmp.close()
    return tmp.name


# ─────────────────────────────────────────────
# TestHelpers
# ─────────────────────────────────────────────

class TestHelpers:
    def test_normalise_strips_trailing_dot(self):
        assert _normalise_key("1.") == "1"

    def test_normalise_leaves_subsection_unchanged(self):
        assert _normalise_key("1.1") == "1.1"

    def test_normalise_leaves_deep_key_unchanged(self):
        assert _normalise_key("3.3.1") == "3.3.1"

    def test_depth_top_level(self):
        assert _section_depth("1") == 1

    def test_depth_second_level(self):
        assert _section_depth("1.1") == 2

    def test_depth_third_level(self):
        assert _section_depth("3.3.1") == 3

    def test_depth_fourth_level(self):
        assert _section_depth("1.2.3.4") == 4


# ─────────────────────────────────────────────
# TestParseSections
# ─────────────────────────────────────────────

class TestParseSections:
    def test_top_level_sections_become_keys(self):
        blocks = [
            "1. Introduction\nThis document describes the facility.",
            "2. The Facility\nThe lender agrees to provide...",
        ]
        result = parse_sections(blocks)
        assert "1" in result
        assert "2" in result

    def test_subsections_become_keys(self):
        blocks = [
            "1. Introduction\nOverview text.",
            "1.1 Background\nBackground detail.",
            "1.2 Scope\nScope detail.",
        ]
        result = parse_sections(blocks)
        assert "1" in result
        assert "1.1" in result
        assert "1.2" in result

    def test_deep_sections_folded_into_parent(self):
        blocks = [
            "1.1 Payment Obligations\nGeneral text.",
            "1.1.1 Principal\nPrincipal repayment terms.",
            "1.1.2 Interest\nInterest accrual terms.",
        ]
        result = parse_sections(blocks)
        assert "1.1" in result
        assert "1.1.1" not in result
        assert "1.1.2" not in result

    def test_deep_section_text_present_under_parent(self):
        blocks = [
            "3.3 Covenants\nGeneral covenant text.",
            "3.3.1 DSCR\nThe DSCR shall not fall below 1.25x.",
            "3.3.2 LTV\nThe LTV shall not exceed 65%.",
        ]
        result = parse_sections(blocks)
        assert "The DSCR shall not fall below 1.25x." in result["3.3"]
        assert "The LTV shall not exceed 65%." in result["3.3"]

    def test_preamble_before_first_section(self):
        blocks = [
            "This agreement is dated 1 January 2026.",
            "1. Definitions\nDefined terms follow.",
        ]
        result = parse_sections(blocks)
        assert "preamble" in result
        assert "1 January 2026" in result["preamble"]

    def test_body_text_between_sections_goes_to_current(self):
        blocks = [
            "2. Representations\nThe borrower represents that:",
            "All statements are true and accurate.",
            "2.1 Financial Condition\nNo material adverse change.",
        ]
        result = parse_sections(blocks)
        assert "All statements are true and accurate." in result["2"]

    def test_section_keys_are_normalised(self):
        # "1." with trailing dot should become key "1", not "1."
        blocks = ["1. Introduction\nText."]
        result = parse_sections(blocks)
        assert "1" in result
        assert "1." not in result

    def test_empty_blocks_list_returns_empty_dict(self):
        assert parse_sections([]) == {}

    def test_section_heading_text_included_in_value(self):
        blocks = ["2.3 Security\nThe borrower shall grant a first charge."]
        result = parse_sections(blocks)
        assert "Security" in result["2.3"]

    def test_multiple_pages_sections_merged_correctly(self):
        # Simulate blocks that span a page boundary within the same section
        blocks = [
            "4. Events of Default\nThe following events constitute default:",
            "Failure to pay any amount when due.",       # continuation on next page
            "4.1 Payment Default\nNon-payment of principal.",
        ]
        result = parse_sections(blocks)
        assert "Failure to pay any amount when due." in result["4"]
        assert "4.1" in result

    def test_section_with_only_number_no_heading_text(self):
        # Edge case: heading line is just the number, text follows on next line
        blocks = ["1.\nThis section covers general provisions."]
        result = parse_sections(blocks)
        assert "1" in result


# ─────────────────────────────────────────────
# TestExtractBlocks
# ─────────────────────────────────────────────

class TestExtractBlocks:
    def test_single_page_blocks_extracted(self):
        path = _make_pdf([["1. Introduction\nOverview.", "1.1 Background\nDetails."]])
        try:
            blocks = extract_blocks(path)
            assert len(blocks) >= 1
            full = " ".join(blocks)
            assert "Introduction" in full
        finally:
            Path(path).unlink(missing_ok=True)

    def test_multi_page_blocks_in_order(self):
        path = _make_pdf([
            ["1. First Section\nContent A."],
            ["2. Second Section\nContent B."],
        ])
        try:
            blocks = extract_blocks(path)
            full = " ".join(blocks)
            assert "First Section" in full
            assert "Second Section" in full
        finally:
            Path(path).unlink(missing_ok=True)

    def test_empty_pdf_returns_no_blocks(self):
        doc = pymupdf.Document()
        doc.new_page()  # blank page
        import tempfile
        tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
        doc.save(tmp.name)
        tmp.close()
        try:
            blocks = extract_blocks(tmp.name)
            assert blocks == []
        finally:
            Path(tmp.name).unlink(missing_ok=True)


# ─────────────────────────────────────────────
# TestIntegration — uses the generated mock PDF
# ─────────────────────────────────────────────

@pytest.mark.skipif(not MOCK_PDF.exists(), reason="mock_document.pdf not found — run generate_mock_pdf.py first")
class TestIntegration:
    """End-to-end tests against files/mock_document.pdf."""

    @pytest.fixture(scope="class")
    def sections(self):
        blocks = extract_blocks(str(MOCK_PDF))
        return parse_sections(blocks)

    def test_all_top_level_sections_present(self, sections):
        for key in ["1", "2", "3", "4", "5", "6"]:
            assert key in sections, f"Missing top-level section: {key}"

    def test_all_subsections_present(self, sections):
        expected = [
            "1.1", "1.2", "1.3",
            "2.1", "2.2", "2.3",
            "3.1", "3.2", "3.3", "3.4",
            "4.1", "4.2",
            "5.1", "5.2",
            "6.1", "6.2", "6.3",
        ]
        for key in expected:
            assert key in sections, f"Missing subsection: {key}"

    def test_deep_sections_not_separate_keys(self, sections):
        for key in ["3.3.1", "3.3.2", "3.3.3"]:
            assert key not in sections, f"Deep section should be folded, not a key: {key}"

    def test_deep_section_text_present_in_parent(self, sections):
        text = sections["3.3"]
        assert "DSCR" in text,  "3.3.1 DSCR content missing from 3.3"
        assert "LTV"  in text,  "3.3.2 LTV content missing from 3.3"
        assert "ICR"  in text,  "3.3.3 ICR content missing from 3.3"

    def test_preamble_captured(self, sections):
        assert "preamble" in sections
        assert "ABC BANK" in sections["preamble"]

    def test_section_text_contains_heading(self, sections):
        assert "DEFINITIONS" in sections["1"]
        assert "FACILITY"    in sections["2"]
        assert "INTEREST"    in sections["3"]
        assert "REPAYMENT"   in sections["4"]

    def test_interest_rate_detail_in_correct_section(self, sections):
        assert "SORA" in sections["3.1"]
        assert "SORA" not in sections["3.2"]

    def test_financial_covenant_values_in_3_3(self, sections):
        text = sections["3.3"]
        assert "1.25" in text   # DSCR floor
        assert "65%"  in text   # LTV cap
        assert "2.00" in text   # ICR floor
